name: Update Ranking
on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        env:
          YGOSU_COOKIE: ${{ secrets.YGOSU_COOKIE }}
        run: |
          pip install requests beautifulsoup4
          python ygosu_analyzer.py
      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git reset --hard origin/main
          git add index.html
          git commit -m "Update ranking" || exit 0
          git push -f origin main
